// <auto-generated />
using AnimalShelter.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace AnimalShelter.Migrations
{
    [DbContext(typeof(AnimalShelterContext))]
    [Migration("20200821185429_AddPagination")]
    partial class AddPagination
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.4-servicing-10062")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("AnimalShelter.Models.Animal", b =>
                {
                    b.Property<int>("AnimalId")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Age")
                        .IsRequired();

                    b.Property<string>("Breed")
                        .IsRequired();

                    b.Property<string>("Coloring")
                        .IsRequired();

                    b.Property<string>("Disposition")
                        .IsRequired();

                    b.Property<string>("EnergyLevel")
                        .IsRequired();

                    b.Property<string>("GetsAlongWith")
                        .IsRequired();

                    b.Property<float>("NumOfFeet");

                    b.Property<string>("Size")
                        .IsRequired();

                    b.Property<string>("Type")
                        .IsRequired();

                    b.HasKey("AnimalId");

                    b.ToTable("Animals");

                    b.HasData(
                        new
                        {
                            AnimalId = 1,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "High",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 2,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Medium",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 3,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Low",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 4,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Slothlike",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 5,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Bouncy",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 6,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Chill",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 7,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Medium",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 8,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Med-Low",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 9,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Highest",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        },
                        new
                        {
                            AnimalId = 10,
                            Age = "1",
                            Breed = "Golden Retriever",
                            Coloring = "Yellow",
                            Disposition = "super sweet",
                            EnergyLevel = "Normal",
                            GetsAlongWith = "Small dogs, children",
                            NumOfFeet = 4f,
                            Size = "Perfect",
                            Type = "Dog"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
